// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Format = require("bs-platform/lib/js/format.js");
var Printf = require("bs-platform/lib/js/printf.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

function default_reason_phrase(param) {
  if (param >= -36288910) {
    if (param >= 398750242) {
      if (param >= 751586522) {
        if (param >= 893234971) {
          if (param >= 1034456810) {
            if (param >= 1052164689) {
              return "Request Timeout";
            } else {
              return "Temporary Redirect";
            }
          } else if (param >= 897427648) {
            return "Expectation Failed";
          } else {
            return "Partial Content";
          }
        } else if (param >= 792903807) {
          return "Gone";
        } else {
          return "URI Too Long";
        }
      } else if (param !== 491839979) {
        if (param >= 566851975) {
          if (param >= 731537414) {
            return "Gateway Timeout";
          } else {
            return "Accepted";
          }
        } else if (param >= 565592383) {
          return "Payload Too Large";
        } else {
          return "Found";
        }
      } else {
        return "I'm a teapot";
      }
    } else if (param >= 102779818) {
      if (param >= 260151748) {
        if (param >= 324098644) {
          if (param >= 384167631) {
            return "Moved Permanently";
          } else {
            return "Unauthorized";
          }
        } else if (param >= 282375460) {
          return "Precondition Failed";
        } else {
          return "See Other";
        }
      } else if (param >= 192584839) {
        return "Continue";
      } else {
        return "Non-Authoritative Information";
      }
    } else if (param !== -12825579) {
      if (param >= 13829438) {
        if (param >= 18898339) {
          return "Multiple Choices";
        } else {
          return "Method Not Allowed";
        }
      } else if (param >= 17692) {
        return "OK";
      } else {
        return "Conflict";
      }
    } else {
      return "Proxy Authentication Required";
    }
  } else if (param >= -527633381) {
    if (param >= -387970219) {
      if (param >= -234002583) {
        if (param >= -176787538) {
          if (param >= -99004555) {
            return "Bad Request";
          } else {
            return "Not Acceptable";
          }
        } else if (param >= -221106440) {
          return "Length Required";
        } else {
          return "Reset Content";
        }
      } else if (param >= -358247754) {
        return "Not Found";
      } else {
        return "Not Modified";
      }
    } else if (param !== -498198474) {
      if (param >= -438114087) {
        if (param >= -398446314) {
          return "Use Proxy";
        } else {
          return "Forbidden";
        }
      } else if (param >= -459143713) {
        return "Unsupported Media Type";
      } else {
        return "No Content";
      }
    } else {
      return "Not Implemented";
    }
  } else if (param >= -785212614) {
    if (param !== -774758938) {
      if (param >= -720017128) {
        if (param >= -558113336) {
          return "Created";
        } else {
          return "Payment Required";
        }
      } else if (param >= -732353682) {
        return "Internal Server Error";
      } else {
        return "Enhance Your Calm";
      }
    } else {
      return "Service Unavailable";
    }
  } else if (param !== -1021676630) {
    if (param >= -957501398) {
      if (param >= -867418942) {
        return "Upgrade Required";
      } else {
        return "Bad Gateway";
      }
    } else if (param >= -1014316796) {
      return "HTTP Version Not Supported";
    } else {
      return "Range Not Satisfiable";
    }
  } else {
    return "Switching Protocols";
  }
}

function to_code(param) {
  if (typeof param === "number") {
    if (param >= -36288910) {
      if (param >= 398750242) {
        if (param >= 751586522) {
          if (param >= 893234971) {
            if (param >= 1034456810) {
              if (param >= 1052164689) {
                return 408;
              } else {
                return 307;
              }
            } else if (param >= 897427648) {
              return 417;
            } else {
              return 206;
            }
          } else if (param >= 792903807) {
            return 410;
          } else {
            return 414;
          }
        } else if (param !== 491839979) {
          if (param >= 566851975) {
            if (param >= 731537414) {
              return 504;
            } else {
              return 202;
            }
          } else if (param >= 565592383) {
            return 413;
          } else {
            return 302;
          }
        } else {
          return 418;
        }
      } else if (param >= 102779818) {
        if (param >= 260151748) {
          if (param >= 324098644) {
            if (param >= 384167631) {
              return 301;
            } else {
              return 401;
            }
          } else if (param >= 282375460) {
            return 412;
          } else {
            return 303;
          }
        } else if (param >= 192584839) {
          return 100;
        } else {
          return 203;
        }
      } else if (param !== -12825579) {
        if (param >= 13829438) {
          if (param >= 18898339) {
            return 300;
          } else {
            return 405;
          }
        } else if (param >= 17692) {
          return 200;
        } else {
          return 409;
        }
      } else {
        return 407;
      }
    } else if (param >= -527633381) {
      if (param >= -387970219) {
        if (param >= -234002583) {
          if (param >= -176787538) {
            if (param >= -99004555) {
              return 400;
            } else {
              return 406;
            }
          } else if (param >= -221106440) {
            return 411;
          } else {
            return 205;
          }
        } else if (param >= -358247754) {
          return 404;
        } else {
          return 304;
        }
      } else if (param !== -498198474) {
        if (param >= -438114087) {
          if (param >= -398446314) {
            return 305;
          } else {
            return 403;
          }
        } else if (param >= -459143713) {
          return 415;
        } else {
          return 204;
        }
      } else {
        return 501;
      }
    } else if (param >= -785212614) {
      if (param !== -774758938) {
        if (param >= -720017128) {
          if (param >= -558113336) {
            return 201;
          } else {
            return 402;
          }
        } else if (param >= -732353682) {
          return 500;
        } else {
          return 420;
        }
      } else {
        return 503;
      }
    } else if (param !== -1021676630) {
      if (param >= -957501398) {
        if (param >= -867418942) {
          return 426;
        } else {
          return 502;
        }
      } else if (param >= -1014316796) {
        return 505;
      } else {
        return 416;
      }
    } else {
      return 101;
    }
  } else {
    return param[1];
  }
}

function really_unsafe_of_code(c) {
  if (c >= 300) {
    if (c < 427) {
      if (c >= 308) {
        if (c >= 400) {
          switch (c - 400 | 0) {
            case 0 : 
                return /* Bad_request */-99004555;
            case 1 : 
                return /* Unauthorized */324098644;
            case 2 : 
                return /* Payment_required */-720017128;
            case 3 : 
                return /* Forbidden */-438114087;
            case 4 : 
                return /* Not_found */-358247754;
            case 5 : 
                return /* Method_not_allowed */13829438;
            case 6 : 
                return /* Not_acceptable */-176787538;
            case 7 : 
                return /* Proxy_authentication_required */-12825579;
            case 8 : 
                return /* Request_timeout */1052164689;
            case 9 : 
                return /* Conflict */-36288910;
            case 10 : 
                return /* Gone */792903807;
            case 11 : 
                return /* Length_required */-221106440;
            case 12 : 
                return /* Precondition_failed */282375460;
            case 13 : 
                return /* Payload_too_large */565592383;
            case 14 : 
                return /* Uri_too_long */751586522;
            case 15 : 
                return /* Unsupported_media_type */-459143713;
            case 16 : 
                return /* Range_not_satisfiable */-1045236833;
            case 17 : 
                return /* Expectation_failed */897427648;
            case 18 : 
                return /* I_m_a_teapot */491839979;
            case 20 : 
                return /* Enhance_your_calm */-785212614;
            case 19 : 
            case 21 : 
            case 22 : 
            case 23 : 
            case 24 : 
            case 25 : 
                return /* `Code */[
                        748543309,
                        c
                      ];
            case 26 : 
                return /* Upgrade_required */-867418942;
            
          }
        } else {
          return /* `Code */[
                  748543309,
                  c
                ];
        }
      } else {
        switch (c - 300 | 0) {
          case 0 : 
              return /* Multiple_choices */18898339;
          case 1 : 
              return /* Moved_permanently */384167631;
          case 2 : 
              return /* Found */398750242;
          case 3 : 
              return /* See_other */260151748;
          case 4 : 
              return /* Not_modified */-387970219;
          case 5 : 
              return /* Use_proxy */-398446314;
          case 6 : 
              return /* `Code */[
                      748543309,
                      c
                    ];
          case 7 : 
              return /* Temporary_redirect */1034456810;
          
        }
      }
    } else {
      switch (c) {
        case 500 : 
            return /* Internal_server_error */-732353682;
        case 501 : 
            return /* Not_implemented */-498198474;
        case 502 : 
            return /* Bad_gateway */-957501398;
        case 503 : 
            return /* Service_unavailable */-774758938;
        case 504 : 
            return /* Gateway_timeout */731537414;
        case 505 : 
            return /* Http_version_not_supported */-1014316796;
        default:
          return /* `Code */[
                  748543309,
                  c
                ];
      }
    }
  } else {
    var switcher = c - 100 | 0;
    if (switcher === 0 || switcher === 1) {
      if (switcher !== 0) {
        return /* Switching_protocols */-1021676630;
      } else {
        return /* Continue */192584839;
      }
    } else {
      switch (switcher) {
        case 100 : 
            return /* OK */17692;
        case 101 : 
            return /* Created */-558113336;
        case 102 : 
            return /* Accepted */566851975;
        case 103 : 
            return /* Non_authoritative_information */102779818;
        case 104 : 
            return /* No_content */-527633381;
        case 105 : 
            return /* Reset_content */-234002583;
        case 106 : 
            return /* Partial_content */893234971;
        default:
          return /* `Code */[
                  748543309,
                  c
                ];
      }
    }
  }
}

function unsafe_of_code(c) {
  var s = really_unsafe_of_code(c);
  if (typeof s === "number" || s[0] !== 748543309) {
    return s;
  } else {
    var c$1 = s[1];
    if (c$1 < 0) {
      return Pervasives.failwith(Curry._1(Printf.sprintf(/* Format */[
                          /* String_literal */Block.__(11, [
                              "Status.unsafe_of_code: ",
                              /* Int */Block.__(4, [
                                  /* Int_d */0,
                                  /* No_padding */0,
                                  /* No_precision */0,
                                  /* String_literal */Block.__(11, [
                                      " is negative",
                                      /* End_of_format */0
                                    ])
                                ])
                            ]),
                          "Status.unsafe_of_code: %d is negative"
                        ]), c$1));
    } else {
      return /* `Code */[
              748543309,
              c$1
            ];
    }
  }
}

function of_code(c) {
  var s = really_unsafe_of_code(c);
  if (typeof s === "number" || s[0] !== 748543309) {
    return s;
  } else {
    var c$1 = s[1];
    if (c$1 < 100 || c$1 > 999) {
      return Pervasives.failwith(Curry._1(Printf.sprintf(/* Format */[
                          /* String_literal */Block.__(11, [
                              "Status.of_code: ",
                              /* Int */Block.__(4, [
                                  /* Int_d */0,
                                  /* No_padding */0,
                                  /* No_precision */0,
                                  /* String_literal */Block.__(11, [
                                      " is not a three-digit number",
                                      /* End_of_format */0
                                    ])
                                ])
                            ]),
                          "Status.of_code: %d is not a three-digit number"
                        ]), c$1));
    } else {
      return /* `Code */[
              748543309,
              c$1
            ];
    }
  }
}

function is_informational(t) {
  if (typeof t === "number") {
    if (t !== -1021676630) {
      return t === 192584839;
    } else {
      return true;
    }
  } else if (t[0] !== 748543309) {
    return false;
  } else {
    var n = t[1];
    if (n >= 100) {
      return n <= 199;
    } else {
      return false;
    }
  }
}

function is_successful(t) {
  if (typeof t === "number") {
    if (t >= 17692) {
      if (t >= 566851975) {
        if (t !== 893234971) {
          return t < 566851976;
        } else {
          return true;
        }
      } else if (t !== 102779818) {
        return t < 17693;
      } else {
        return true;
      }
    } else if (t !== -558113336 && t !== -527633381) {
      return t === -234002583;
    } else {
      return true;
    }
  } else if (t[0] !== 748543309) {
    return false;
  } else {
    var n = t[1];
    if (n >= 200) {
      return n <= 299;
    } else {
      return false;
    }
  }
}

function is_redirection(t) {
  if (typeof t === "number") {
    if (t >= 260151748) {
      if (t >= 398750242) {
        if (t !== 1034456810) {
          return t < 398750243;
        } else {
          return true;
        }
      } else if (t !== 384167631) {
        return t < 260151749;
      } else {
        return true;
      }
    } else if (t !== -398446314 && t !== -387970219) {
      return t === 18898339;
    } else {
      return true;
    }
  } else if (t[0] !== 748543309) {
    return false;
  } else {
    var n = t[1];
    if (n >= 300) {
      return n <= 399;
    } else {
      return false;
    }
  }
}

function is_client_error(t) {
  if (typeof t === "number") {
    if (t >= -36288910) {
      if (t >= 491839980) {
        if (t >= 792903807) {
          if (t !== 897427648 && t !== 1052164689) {
            return t < 792903808;
          } else {
            return true;
          }
        } else if (t !== 565592383) {
          return t === 751586522;
        } else {
          return true;
        }
      } else if (t >= 13829439) {
        if (t !== 282375460 && t !== 324098644) {
          return t >= 491839979;
        } else {
          return true;
        }
      } else if (t !== -12825579 && t >= -36288909) {
        return t >= 13829438;
      } else {
        return true;
      }
    } else if (t >= -459143712) {
      if (t >= -221106440) {
        if (t !== -176787538 && t !== -99004555) {
          return t < -221106439;
        } else {
          return true;
        }
      } else if (t !== -438114087) {
        return t === -358247754;
      } else {
        return true;
      }
    } else if (t >= -785212614) {
      if (t !== -720017128 && t >= -785212613) {
        return t >= -459143713;
      } else {
        return true;
      }
    } else if (t !== -1045236833) {
      return t === -867418942;
    } else {
      return true;
    }
  } else if (t[0] !== 748543309) {
    return false;
  } else {
    var n = t[1];
    if (n >= 400) {
      return n <= 499;
    } else {
      return false;
    }
  }
}

function is_server_error(t) {
  if (typeof t === "number") {
    if (t >= -774758937) {
      if (t !== -732353682 && t !== -498198474) {
        return t === 731537414;
      } else {
        return true;
      }
    } else if (t !== -1014316796 && t !== -957501398) {
      return t >= -774758938;
    } else {
      return true;
    }
  } else if (t[0] !== 748543309) {
    return false;
  } else {
    var n = t[1];
    if (n >= 500) {
      return n <= 599;
    } else {
      return false;
    }
  }
}

function is_error(t) {
  if (is_client_error(t)) {
    return true;
  } else {
    return is_server_error(t);
  }
}

function to_string(param) {
  if (typeof param === "number") {
    if (param >= -36288910) {
      if (param >= 398750242) {
        if (param >= 751586522) {
          if (param >= 893234971) {
            if (param >= 1034456810) {
              if (param >= 1052164689) {
                return "408";
              } else {
                return "307";
              }
            } else if (param >= 897427648) {
              return "417";
            } else {
              return "206";
            }
          } else if (param >= 792903807) {
            return "410";
          } else {
            return "414";
          }
        } else if (param !== 491839979) {
          if (param >= 566851975) {
            if (param >= 731537414) {
              return "504";
            } else {
              return "202";
            }
          } else if (param >= 565592383) {
            return "413";
          } else {
            return "302";
          }
        } else {
          return "418";
        }
      } else if (param >= 102779818) {
        if (param >= 260151748) {
          if (param >= 324098644) {
            if (param >= 384167631) {
              return "301";
            } else {
              return "401";
            }
          } else if (param >= 282375460) {
            return "412";
          } else {
            return "303";
          }
        } else if (param >= 192584839) {
          return "100";
        } else {
          return "203";
        }
      } else if (param !== -12825579) {
        if (param >= 13829438) {
          if (param >= 18898339) {
            return "300";
          } else {
            return "405";
          }
        } else if (param >= 17692) {
          return "200";
        } else {
          return "409";
        }
      } else {
        return "407";
      }
    } else if (param >= -527633381) {
      if (param >= -387970219) {
        if (param >= -234002583) {
          if (param >= -176787538) {
            if (param >= -99004555) {
              return "400";
            } else {
              return "406";
            }
          } else if (param >= -221106440) {
            return "411";
          } else {
            return "205";
          }
        } else if (param >= -358247754) {
          return "404";
        } else {
          return "304";
        }
      } else if (param !== -498198474) {
        if (param >= -438114087) {
          if (param >= -398446314) {
            return "305";
          } else {
            return "403";
          }
        } else if (param >= -459143713) {
          return "415";
        } else {
          return "204";
        }
      } else {
        return "501";
      }
    } else if (param >= -785212614) {
      if (param !== -774758938) {
        if (param >= -720017128) {
          if (param >= -558113336) {
            return "201";
          } else {
            return "402";
          }
        } else if (param >= -732353682) {
          return "500";
        } else {
          return "420";
        }
      } else {
        return "503";
      }
    } else if (param !== -1021676630) {
      if (param >= -957501398) {
        if (param >= -867418942) {
          return "426";
        } else {
          return "502";
        }
      } else if (param >= -1014316796) {
        return "505";
      } else {
        return "416";
      }
    } else {
      return "101";
    }
  } else {
    return String(param[1]);
  }
}

function of_string(x) {
  return of_code(Caml_format.caml_int_of_string(x));
}

function pp_hum(fmt, t) {
  return Curry._1(Format.fprintf(fmt, /* Format */[
                  /* Int */Block.__(4, [
                      /* Int_u */12,
                      /* No_padding */0,
                      /* No_precision */0,
                      /* End_of_format */0
                    ]),
                  "%u"
                ]), to_code(t));
}

exports.default_reason_phrase = default_reason_phrase;
exports.to_code = to_code;
exports.really_unsafe_of_code = really_unsafe_of_code;
exports.unsafe_of_code = unsafe_of_code;
exports.of_code = of_code;
exports.is_informational = is_informational;
exports.is_successful = is_successful;
exports.is_redirection = is_redirection;
exports.is_client_error = is_client_error;
exports.is_server_error = is_server_error;
exports.is_error = is_error;
exports.to_string = to_string;
exports.of_string = of_string;
exports.pp_hum = pp_hum;
/* Format Not a pure module */
